"use strict";
/**
 * RUIT CBE — Complete Event Registry
 * All 48 event types for the events table (append-only)
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ALL_EVENT_TYPES = exports.EVENT_TYPES = void 0;
exports.EVENT_TYPES = {
    // USER / IDENTITY
    USER_REGISTERED: 'USER_REGISTERED',
    KYC_DOCUMENT_UPLOADED: 'KYC_DOCUMENT_UPLOADED',
    KYC_APPROVED: 'KYC_APPROVED',
    KYC_REJECTED: 'KYC_REJECTED',
    TRUST_SCORE_UPDATED: 'TRUST_SCORE_UPDATED',
    TRUST_WARNING: 'TRUST_WARNING',
    TIER5_ELIGIBILITY_REACHED: 'TIER5_ELIGIBILITY_REACHED',
    INSURANCE_EXPIRY_WARNING: 'INSURANCE_EXPIRY_WARNING',
    LICENSE_EXPIRY_WARNING: 'LICENSE_EXPIRY_WARNING',
    CROSS_TENANT_ACCESS: 'CROSS_TENANT_ACCESS',
    // LOAD
    LOAD_CREATED: 'LOAD_CREATED',
    QUOTE_GENERATED: 'QUOTE_GENERATED',
    QUOTE_ACCEPTED: 'QUOTE_ACCEPTED',
    QUOTE_REJECTED: 'QUOTE_REJECTED',
    NEGOTIATION_ROUND: 'NEGOTIATION_ROUND',
    LOAD_EXHAUSTED_ATTEMPTS: 'LOAD_EXHAUSTED_ATTEMPTS',
    LOAD_CANCELLED: 'LOAD_CANCELLED',
    LOAD_STATUS_CHANGED: 'LOAD_STATUS_CHANGED',
    // ASSIGNMENT
    ASSIGNMENT_SUGGESTED: 'ASSIGNMENT_SUGGESTED',
    ASSIGNMENT_ACCEPTED: 'ASSIGNMENT_ACCEPTED',
    ASSIGNMENT_REJECTED: 'ASSIGNMENT_REJECTED',
    ASSIGNMENT_EXPIRED: 'ASSIGNMENT_EXPIRED',
    // TRIP
    PICKUP_CONFIRMED: 'PICKUP_CONFIRMED',
    GPS_TRACE_BATCH: 'GPS_TRACE_BATCH',
    DEVIATION_DETECTED: 'DEVIATION_DETECTED',
    IDLE_ALERT: 'IDLE_ALERT',
    DELIVERY_CONFIRMED: 'DELIVERY_CONFIRMED',
    POD_UPLOADED: 'POD_UPLOADED',
    TRIP_ROAD_CONDITION_REPORTED: 'TRIP_ROAD_CONDITION_REPORTED',
    USSD_POD_OVERDUE: 'USSD_POD_OVERDUE',
    // FINANCIAL
    ESCROW_HELD: 'ESCROW_HELD',
    PAYMENT_RELEASED: 'PAYMENT_RELEASED',
    PAYMENT_DELAYED: 'PAYMENT_DELAYED',
    EXPOSURE_CAP_WARNING: 'EXPOSURE_CAP_WARNING',
    EXPOSURE_CAP_BREACHED: 'EXPOSURE_CAP_BREACHED',
    COD_DISCREPANCY_REPORTED: 'COD_DISCREPANCY_REPORTED',
    // TRUCK / DATA
    FUEL_LOG_SUBMITTED: 'FUEL_LOG_SUBMITTED',
    // INCIDENT
    INCIDENT_OPENED: 'INCIDENT_OPENED',
    EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
    INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
    DISPUTE_ESCALATED: 'DISPUTE_ESCALATED',
    // CORRIDOR
    CORRIDOR_HEALTH_UPDATED: 'CORRIDOR_HEALTH_UPDATED',
    CORRIDOR_FROZEN: 'CORRIDOR_FROZEN',
    CORRIDOR_INSUFFICIENT_STATS_WARNING: 'CORRIDOR_INSUFFICIENT_STATS_WARNING',
    // SHOCK / SYSTEM
    SHOCK_MODE_ACTIVATED: 'SHOCK_MODE_ACTIVATED',
    SHOCK_MODE_DEACTIVATED: 'SHOCK_MODE_DEACTIVATED',
    FUEL_QUEUE_MODE_ACTIVATED: 'FUEL_QUEUE_MODE_ACTIVATED',
    STRATEGY_VERSION_CHANGED: 'STRATEGY_VERSION_CHANGED',
    // FRAUD
    FRAUD_FLAG_RAISED: 'FRAUD_FLAG_RAISED',
    COLLUSION_DETECTED: 'COLLUSION_DETECTED',
    // OPS / GOVERNANCE
    MANUAL_OVERRIDE_ISSUED: 'MANUAL_OVERRIDE_ISSUED',
    WEBHOOK_TRIGGERED: 'WEBHOOK_TRIGGERED',
    ZONE_DEMAND_OVERRIDE: 'ZONE_DEMAND_OVERRIDE',
    // Medium-Haul Platform Events
    BACKHAUL_SUGGESTED: 'BACKHAUL_SUGGESTED',
    BACKHAUL_ACCEPTED: 'BACKHAUL_ACCEPTED',
    BACKHAUL_REJECTED: 'BACKHAUL_REJECTED',
    BACKHAUL_EXPIRED: 'BACKHAUL_EXPIRED',
    TRUCK_IDLE_ALERT: 'TRUCK_IDLE_ALERT',
    OVERLOAD_DETECTED: 'OVERLOAD_DETECTED',
    WEIGHBRIDGE_ENCOUNTERED: 'WEIGHBRIDGE_ENCOUNTERED',
    FUEL_PRICE_UPDATED: 'FUEL_PRICE_UPDATED',
    FUEL_SHORTAGE_REPORTED: 'FUEL_SHORTAGE_REPORTED',
    ZONE_CONGESTION_DETECTED: 'ZONE_CONGESTION_DETECTED',
    ZONE_CONGESTION_CLEARED: 'ZONE_CONGESTION_CLEARED',
    TEMPLATE_AUTO_POSTED: 'TEMPLATE_AUTO_POSTED',
    TEMPLATE_CREATED: 'TEMPLATE_CREATED',
    ROUTE_DEVIATION_DETECTED: 'ROUTE_DEVIATION_DETECTED',
    ROUTE_DEVIATION_RESOLVED: 'ROUTE_DEVIATION_RESOLVED',
    CHECKPOINT_INTELLIGENCE_UPDATED: 'CHECKPOINT_INTELLIGENCE_UPDATED',
    ROAD_CONDITION_DEGRADED: 'ROAD_CONDITION_DEGRADED',
    CONSOLIDATION_CREATED: 'CONSOLIDATION_CREATED',
    SUB_LOAD_JOINED: 'SUB_LOAD_JOINED',
    SUB_LOAD_CANCELLED: 'SUB_LOAD_CANCELLED',
    CONSOLIDATION_DISPATCHED: 'CONSOLIDATION_DISPATCHED',
    CONSOLIDATION_SHORTFALL_APPLIED: 'CONSOLIDATION_SHORTFALL_APPLIED',
    BROKER_SUGGESTION_CREATED: 'BROKER_SUGGESTION_CREATED',
    BROKER_SUGGESTION_ACCEPTED: 'BROKER_SUGGESTION_ACCEPTED',
    DRIVER_BONUS_EARNED: 'DRIVER_BONUS_EARNED',
    VOUCHER_ISSUED: 'VOUCHER_ISSUED',
    VOUCHER_REDEEMED: 'VOUCHER_REDEEMED',
    REFERRAL_QUALIFIED: 'REFERRAL_QUALIFIED',
    RECOVERY_RESOURCE_REQUESTED: 'RECOVERY_RESOURCE_REQUESTED',
    TERMINAL_QUEUE_JOINED: 'TERMINAL_QUEUE_JOINED',
    TERMINAL_QUEUE_DROPPED: 'TERMINAL_QUEUE_DROPPED',
    SHADOW_BROKER_SUSPECTED: 'SHADOW_BROKER_SUSPECTED',
    DISPUTE_SLA_BREACH: 'DISPUTE_SLA_BREACH',
    MAINTENANCE_STATUS_SET: 'MAINTENANCE_STATUS_SET',
    // Phase 2 Additions
    BROKER_REGISTERED: 'BROKER_REGISTERED',
    BROKER_VERIFIED: 'BROKER_VERIFIED',
    BROKER_SUSPENDED: 'BROKER_SUSPENDED',
    AGENT_REGISTERED: 'AGENT_REGISTERED',
    CHECKPOINT_LOGGED: 'CHECKPOINT_LOGGED',
    COMPLIANCE_UPDATE: 'COMPLIANCE_UPDATE',
    // Phase 9 Additions
    ROAD_ALERT_CREATED: 'ROAD_ALERT_CREATED',
    MAINTENANCE_REMINDER_SENT: 'MAINTENANCE_REMINDER_SENT',
    // Phase 10: Cargo-Specific Features
    COLD_CHAIN_EXCURSION_ALERT: 'COLD_CHAIN_EXCURSION_ALERT',
    TEMPERATURE_LOGGED: 'TEMPERATURE_LOGGED',
    COMPLIANCE_CERTIFICATE_GENERATED: 'COMPLIANCE_CERTIFICATE_GENERATED',
    LIVESTOCK_MORTALITY_REPORTED: 'LIVESTOCK_MORTALITY_REPORTED',
    TIME_CRITICAL_LOAD_CREATED: 'TIME_CRITICAL_LOAD_CREATED',
};
exports.ALL_EVENT_TYPES = Object.values(exports.EVENT_TYPES);
//# sourceMappingURL=events.js.map