"use strict";
/**
 * RUIT CBE — Entity Status Enums and Constants
 * All enums from the database schema
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DRIVER_EARNING_STATUS = exports.DRIVER_EARNING_TYPE = exports.BROKER_SUGGESTION_STATUS = exports.CONSOLIDATION_SHORTFALL_POLICY = exports.AGGREGATOR_TYPE = exports.SUB_LOAD_STATUS = exports.CONSOLIDATED_LOAD_STATUS = exports.BACKHAUL_STATUS = exports.FUEL_TYPE = exports.TRUCK_BRAND = exports.CORRIDOR_TYPE = exports.PAYOUT_SPEED = exports.URGENCY_LEVEL = exports.DEMAND_IMPACT = exports.ET_EVENT_NAME = exports.MAINTENANCE_TYPE = exports.TX_STATUS = exports.EXPENSE_TYPE = exports.TX_DIRECTION = exports.CHECKPOINT_TYPE = exports.NOTIFICATION_CHANNEL = exports.BUSINESS_TYPE = exports.BUSINESS_SECTOR = exports.DRIVER_STATUS = exports.CORRIDOR_STATUS = exports.ROAD_TYPE = exports.SHOCK_TYPE = exports.FRAUD_SEVERITY = exports.INCIDENT_TYPE = exports.EXPOSURE_SCOPE = exports.COMMISSION_CONFIG_TYPE = exports.OPTIMIZATION_MODE = exports.REGION = exports.TX_TYPE = exports.KYC_DOC_TYPE = exports.COLD_CHAIN_CARGO_TYPES = exports.PAYMENT_BASIS = exports.LIVESTOCK_SPECIES = exports.TIME_CRITICAL_CARGO_TYPES = exports.CARGO_TYPE = exports.TRUCK_TYPE = exports.TRUCK_BODY_TYPE = exports.PAYMENT_MODEL = exports.INCIDENT_SEVERITY = exports.INCIDENT_STATUS = exports.ASSIGNMENT_STATUS = exports.TRIP_STATUS = exports.LOAD_STATUS = exports.TRUCK_STATUS = exports.USER_STATUS = void 0;
exports.FUEL_AVAILABILITY_STATUS = exports.ROAD_ALERT_TYPES = exports.AGENT_TYPE = exports.FUEL_PRICE_SOURCE = exports.SHIFT_DAY = exports.REFERRAL_STATUS = exports.TRIP_EVENT_RECONCILIATION_STATUS = exports.TRIP_EVENT_TYPE = exports.RECOVERY_RESOURCE_TYPE = exports.VOUCHER_STATUS = exports.LIQUIDITY_INCENTIVE_TYPE = void 0;
// User Status
exports.USER_STATUS = {
    PENDING_KYC: 'PENDING_KYC',
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    BLACKLISTED: 'BLACKLISTED',
};
// Truck Status
exports.TRUCK_STATUS = {
    ACTIVE: 'ACTIVE',
    ON_TRIP: 'ON_TRIP',
    MAINTENANCE: 'MAINTENANCE',
    SUSPENDED: 'SUSPENDED',
    RETIRED: 'RETIRED',
};
// Load Status
exports.LOAD_STATUS = {
    DRAFT: 'DRAFT',
    OPEN: 'OPEN',
    QUOTING: 'QUOTING',
    MATCHED: 'MATCHED',
    READY_TO_MATCH: 'READY_TO_MATCH',
    DEPARTED: 'DEPARTED',
    IN_TRANSIT: 'IN_TRANSIT',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
    DISPUTED: 'DISPUTED',
};
// Trip Status
exports.TRIP_STATUS = {
    PENDING: 'PENDING',
    EN_ROUTE: 'EN_ROUTE',
    AT_CHECKPOINT: 'AT_CHECKPOINT',
    DELIVERED: 'DELIVERED',
    DISPUTED: 'DISPUTED',
    CANCELLED: 'CANCELLED',
    DELAYED: 'DELAYED',
    EMERGENCY: 'EMERGENCY',
};
// Assignment Status
exports.ASSIGNMENT_STATUS = {
    SUGGESTED: 'SUGGESTED',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
};
// Incident Status
exports.INCIDENT_STATUS = {
    OPEN: 'OPEN',
    UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
    EVIDENCE_COLLECTION: 'EVIDENCE_COLLECTION',
    AWAITING_RESOLUTION: 'AWAITING_RESOLUTION',
    RESOLVED: 'RESOLVED',
    ESCALATED: 'ESCALATED',
    CLOSED: 'CLOSED',
};
// Incident Severity
exports.INCIDENT_SEVERITY = {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
};
// Payment Model
exports.PAYMENT_MODEL = {
    ESCROW: 'ESCROW',
    COD: 'COD',
    ROLLING_CREDIT: 'ROLLING_CREDIT',
    PARTIAL_ADVANCE: 'PARTIAL_ADVANCE',
};
// Truck Type
exports.TRUCK_BODY_TYPE = {
    FLATBED: 'FLATBED',
    COVERED: 'COVERED',
    REFRIGERATED: 'REFRIGERATED',
    TANKER: 'TANKER',
    TIPPER: 'TIPPER',
    LOWBED: 'LOWBED',
    LIVESTOCK: 'LIVESTOCK',
    OTHER: 'OTHER',
};
exports.TRUCK_TYPE = {
    FLATBED: 'FLATBED',
    REEFER: 'REEFER',
    TANKER: 'TANKER',
    BOX: 'BOX',
    TIPPER: 'TIPPER',
    CURTAINSIDER: 'CURTAINSIDER',
};
// Cargo Type
exports.CARGO_TYPE = {
    GENERAL: 'GENERAL',
    PERISHABLE: 'PERISHABLE',
    HAZMAT: 'HAZMAT',
    LIVESTOCK: 'LIVESTOCK',
    FMCG: 'FMCG',
    CONSTRUCTION: 'CONSTRUCTION',
    AGRICULTURE: 'AGRICULTURE',
    // Phase 10: New cargo types
    KHAT: 'KHAT',
    FRESH_FISH: 'FRESH_FISH',
    CUT_FLOWERS: 'CUT_FLOWERS',
    FROZEN_MEAT: 'FROZEN_MEAT',
    FRESH_PRODUCE: 'FRESH_PRODUCE',
    DAIRY: 'DAIRY',
    BAGGED_GRAIN: 'BAGGED_GRAIN',
    CEMENT: 'CEMENT',
    BEVERAGES: 'BEVERAGES',
    COFFEE: 'COFFEE',
    COTTON_SESAME: 'COTTON_SESAME',
    HONEY: 'HONEY',
};
// Phase 10: Time-critical cargo types
exports.TIME_CRITICAL_CARGO_TYPES = [
    exports.CARGO_TYPE.KHAT,
    exports.CARGO_TYPE.FRESH_FISH,
    exports.CARGO_TYPE.CUT_FLOWERS,
    exports.CARGO_TYPE.FROZEN_MEAT,
    exports.CARGO_TYPE.FRESH_PRODUCE,
    exports.CARGO_TYPE.DAIRY,
];
// Phase 10: Livestock species
exports.LIVESTOCK_SPECIES = {
    CATTLE: 'cattle',
    SHEEP: 'sheep',
    POULTRY: 'poultry',
};
// Phase 10: Payment basis
exports.PAYMENT_BASIS = {
    PER_KG: 'PER_KG',
    PER_HEAD: 'PER_HEAD',
};
// Phase 10: Cold chain cargo types
exports.COLD_CHAIN_CARGO_TYPES = [
    exports.CARGO_TYPE.FROZEN_MEAT,
    exports.CARGO_TYPE.FRESH_PRODUCE,
    exports.CARGO_TYPE.DAIRY,
    exports.CARGO_TYPE.CUT_FLOWERS,
];
// KYC Document Type
exports.KYC_DOC_TYPE = {
    NATIONAL_ID: 'NATIONAL_ID',
    KEBELE_ID: 'KEBELE_ID',
    PASSPORT: 'PASSPORT',
    TRADE_LICENSE: 'TRADE_LICENSE',
    TIN_CERT: 'TIN_CERT',
    INSURANCE: 'INSURANCE',
    INSPECTION: 'INSPECTION',
    DRIVER_LICENSE: 'DRIVER_LICENSE',
    BANK_STATEMENT: 'BANK_STATEMENT',
    VEHICLE_LOG_BOOK: 'VEHICLE_LOG_BOOK',
};
// Transaction Type
exports.TX_TYPE = {
    ESCROW_HOLD: 'ESCROW_HOLD',
    ESCROW_RELEASE: 'ESCROW_RELEASE',
    ADVANCE_PAYOUT: 'ADVANCE_PAYOUT',
    COMMISSION_DEDUCTION: 'COMMISSION_DEDUCTION',
    COD_LOG: 'COD_LOG',
    PENALTY: 'PENALTY',
    CREDIT_DRAWDOWN: 'CREDIT_DRAWDOWN',
    REFUND: 'REFUND',
    ADJUSTMENT: 'ADJUSTMENT',
};
// Regional corridors
exports.REGION = {
    NORTH: 'NORTH',
    SOUTH: 'SOUTH',
    EAST: 'EAST',
    WEST: 'WEST',
    CENTRAL: 'CENTRAL',
};
// Optimization Mode
exports.OPTIMIZATION_MODE = {
    GROWTH: 'GROWTH',
    DENSITY: 'DENSITY',
    EFFICIENCY: 'EFFICIENCY',
    SHOCK: 'SHOCK',
};
// Commission Config Type
exports.COMMISSION_CONFIG_TYPE = {
    PERCENTAGE: 'PERCENTAGE',
    FIXED: 'FIXED',
    TIERED: 'TIERED',
};
// Exposure Cap Scope
exports.EXPOSURE_SCOPE = {
    CLIENT: 'CLIENT',
    FLEET: 'FLEET',
    CORRIDOR: 'CORRIDOR',
    SYSTEM: 'SYSTEM',
    CLUSTER: 'CLUSTER',
};
// Incident Type
exports.INCIDENT_TYPE = {
    LATE_DELIVERY: 'LATE_DELIVERY',
    CARGO_DAMAGE: 'CARGO_DAMAGE',
    ROUTE_DEVIATION: 'ROUTE_DEVIATION',
    FRAUD: 'FRAUD',
    ACCIDENT: 'ACCIDENT',
    BREAKDOWN: 'BREAKDOWN',
    DISPUTE: 'DISPUTE',
    CARGO_SHORTAGE: 'CARGO_SHORTAGE',
    WRONG_DELIVERY: 'WRONG_DELIVERY',
    SOS: 'SOS',
    CHECKPOINT_FEE: 'CHECKPOINT_FEE',
    CARGO_DAMAGE_AT_PICKUP: 'CARGO_DAMAGE_AT_PICKUP',
    CARGO_DAMAGE_AT_DELIVERY: 'CARGO_DAMAGE_AT_DELIVERY',
    DEMURRAGE: 'DEMURRAGE',
    LOAD_CANCELLED: 'LOAD_CANCELLED',
};
// Fraud Severity
exports.FRAUD_SEVERITY = {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
};
// Shock Type
exports.SHOCK_TYPE = {
    FUEL_SHORTAGE: 'FUEL_SHORTAGE',
    ROAD_CLOSURE: 'ROAD_CLOSURE',
    POLITICAL: 'POLITICAL',
    WEATHER: 'WEATHER',
    PAYMENT_CRISIS: 'PAYMENT_CRISIS',
    MANUAL: 'MANUAL',
};
// Road Type
exports.ROAD_TYPE = {
    ASPHALT: 'ASPHALT',
    GRAVEL: 'GRAVEL',
    MIXED: 'MIXED',
};
// Corridor Status
exports.CORRIDOR_STATUS = {
    ACTIVE: 'ACTIVE',
    FROZEN: 'FROZEN',
    SEEDING: 'SEEDING',
    DEPRECATED: 'DEPRECATED',
};
// Driver Status
exports.DRIVER_STATUS = {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    BLACKLISTED: 'BLACKLISTED',
    ON_TRIP: 'ON_TRIP',
    AVAILABLE: 'AVAILABLE',
    RESTING: 'RESTING',
    UNAVAILABLE: 'UNAVAILABLE',
};
// Business Sector
exports.BUSINESS_SECTOR = {
    FMCG: 'FMCG',
    AGRICULTURE: 'AGRICULTURE',
    MANUFACTURING: 'MANUFACTURING',
    CONSTRUCTION: 'CONSTRUCTION',
    RETAIL: 'RETAIL',
    OTHER: 'OTHER',
};
// Business Type
exports.BUSINESS_TYPE = {
    SOLE_TRADER: 'SOLE_TRADER',
    COMPANY: 'COMPANY',
    COOPERATIVE: 'COOPERATIVE',
};
// Notification Channel
exports.NOTIFICATION_CHANNEL = {
    SMS: 'SMS',
    PUSH: 'PUSH',
    BOTH: 'BOTH',
};
// Checkpoint Type
exports.CHECKPOINT_TYPE = {
    POLICE: 'POLICE',
    WEIGHBRIDGE: 'WEIGHBRIDGE',
    TOLL: 'TOLL',
    FUEL_POINT: 'FUEL_POINT',
    CITY_BOUNDARY: 'CITY_BOUNDARY',
    CUSTOMS: 'CUSTOMS',
};
// Transaction Direction
exports.TX_DIRECTION = {
    IN: 'IN',
    OUT: 'OUT',
};
// Expense Type
exports.EXPENSE_TYPE = {
    FUEL: 'FUEL',
    MAINTENANCE: 'MAINTENANCE',
    SALARY: 'SALARY',
    INSURANCE: 'INSURANCE',
    LOAN: 'LOAN',
    CHECKPOINT_FEE: 'CHECKPOINT_FEE',
    LOADING_FEE: 'LOADING_FEE',
    OTHER: 'OTHER',
};
// Transaction Status
exports.TX_STATUS = {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REVERSED: 'REVERSED',
    DISPUTED: 'DISPUTED',
};
// Maintenance Type
exports.MAINTENANCE_TYPE = {
    OIL_CHANGE: 'OIL_CHANGE',
    TYRE_ROTATION: 'TYRE_ROTATION',
    BRAKE_SERVICE: 'BRAKE_SERVICE',
    ENGINE_SERVICE: 'ENGINE_SERVICE',
    FULL_SERVICE: 'FULL_SERVICE',
    REPAIR: 'REPAIR',
};
// Event Types List
exports.ET_EVENT_NAME = {
    TIMKAT: 'TIMKAT',
    ENKUTATASH: 'ENKUTATASH',
    IRREECHA: 'IRREECHA',
    FASIKA: 'FASIKA',
    GENA: 'GENA',
    MAWLID: 'MAWLID',
    RAMADAN_START: 'RAMADAN_START',
    RAMADAN_END: 'RAMADAN_END',
    MARKET_DAY: 'MARKET_DAY',
    HARVEST_BELG: 'HARVEST_BELG',
    HARVEST_MEHER: 'HARVEST_MEHER',
    NATIONAL_HOLIDAY: 'NATIONAL_HOLIDAY',
};
// Demand Impact
exports.DEMAND_IMPACT = {
    HIGH_DEMAND: 'HIGH_DEMAND',
    LOW_DEMAND: 'LOW_DEMAND',
    NEUTRAL: 'NEUTRAL',
    ROUTE_DISRUPTION: 'ROUTE_DISRUPTION',
};
// Priority Levels
exports.URGENCY_LEVEL = {
    FLEXIBLE: 1,
    NORMAL: 2,
    URGENT: 3,
    CRITICAL: 4,
};
// Payout Speed
exports.PAYOUT_SPEED = {
    T0: 'T0',
    T1: 'T1',
    T3: 'T3',
    T7: 'T7',
};
// Medium-Haul Platform Enums
exports.CORRIDOR_TYPE = {
    INTERCITY: 'INTERCITY',
    INTRACITY: 'INTRACITY',
    REGIONAL: 'REGIONAL',
};
exports.TRUCK_BRAND = {
    ISUZU: 'ISUZU',
    TATA: 'TATA',
    SINO: 'SINO',
    FAW: 'FAW',
    FOTON: 'FOTON',
    HINO: 'HINO',
    MERCEDES: 'MERCEDES',
    ASHOK_LEYLAND: 'ASHOK_LEYLAND',
    OTHER: 'OTHER',
};
exports.FUEL_TYPE = {
    DIESEL: 'DIESEL',
    PETROL: 'PETROL',
};
exports.BACKHAUL_STATUS = {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED',
};
exports.CONSOLIDATED_LOAD_STATUS = {
    COLLECTING: 'COLLECTING',
    READY: 'READY',
    IN_TRANSIT: 'IN_TRANSIT',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
};
exports.SUB_LOAD_STATUS = {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    CANCELLED: 'CANCELLED',
    DELIVERED: 'DELIVERED',
};
exports.AGGREGATOR_TYPE = {
    FIELD_AGENT: 'FIELD_AGENT',
    CONSOLIDATION_AGENT: 'CONSOLIDATION_AGENT',
    ERP_SYSTEM: 'ERP_SYSTEM',
    SELF_ORGANIZED: 'SELF_ORGANIZED',
};
exports.CONSOLIDATION_SHORTFALL_POLICY = {
    PLATFORM_ABSORB: 'PLATFORM_ABSORB',
    DISTRIBUTE: 'DISTRIBUTE',
    AGENT_BEARS: 'AGENT_BEARS',
};
exports.BROKER_SUGGESTION_STATUS = {
    PENDING: 'PENDING',
    FLEET_ACCEPTED: 'FLEET_ACCEPTED',
    ORDERER_ACCEPTED: 'ORDERER_ACCEPTED',
    BOTH_ACCEPTED: 'BOTH_ACCEPTED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED',
};
exports.DRIVER_EARNING_TYPE = {
    ON_TIME_BONUS: 'ON_TIME_BONUS',
    CHECKPOINT_BONUS: 'CHECKPOINT_BONUS',
    FUEL_REPORT_BONUS: 'FUEL_REPORT_BONUS',
    BACKHAUL_BONUS: 'BACKHAUL_BONUS',
    PERFECT_WEEK: 'PERFECT_WEEK',
    ROAD_ALERT_BONUS: 'ROAD_ALERT_BONUS',
};
exports.DRIVER_EARNING_STATUS = {
    PENDING: 'PENDING',
    PAID: 'PAID',
};
exports.LIQUIDITY_INCENTIVE_TYPE = {
    GUARANTEED_MINIMUM: 'GUARANTEED_MINIMUM',
    FUEL_SUBSIDY: 'FUEL_SUBSIDY',
    BROKER_BONUS: 'BROKER_BONUS',
    DRIVER_BONUS: 'DRIVER_BONUS',
};
exports.VOUCHER_STATUS = {
    ACTIVE: 'ACTIVE',
    REDEEMED: 'REDEEMED',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
};
exports.RECOVERY_RESOURCE_TYPE = {
    MECHANIC: 'MECHANIC',
    TOW_TRUCK: 'TOW_TRUCK',
    REPLACEMENT_TRUCK: 'REPLACEMENT_TRUCK',
    FUEL_DELIVERY: 'FUEL_DELIVERY',
};
exports.TRIP_EVENT_TYPE = {
    PICKUP_CONFIRMED: 'PICKUP_CONFIRMED',
    CHECKPOINT_LOGGED: 'CHECKPOINT_LOGGED',
    DELIVERY_CONFIRMED: 'DELIVERY_CONFIRMED',
    CARGO_CONDITION_RECORDED: 'CARGO_CONDITION_RECORDED',
    SOS_TRIGGERED: 'SOS_TRIGGERED',
    INCIDENT_REPORTED: 'INCIDENT_REPORTED',
};
exports.TRIP_EVENT_RECONCILIATION_STATUS = {
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    REQUIRES_REVIEW: 'REQUIRES_REVIEW',
};
exports.REFERRAL_STATUS = {
    PENDING: 'PENDING',
    QUALIFIED: 'QUALIFIED',
    REWARDED: 'REWARDED',
};
exports.SHIFT_DAY = {
    MON: 'MON',
    TUE: 'TUE',
    WED: 'WED',
    THU: 'THU',
    FRI: 'FRI',
    SAT: 'SAT',
    SUN: 'SUN',
};
exports.FUEL_PRICE_SOURCE = {
    MANUAL: 'MANUAL',
    DRIVER_REPORT: 'DRIVER_REPORT',
    API: 'API',
};
exports.AGENT_TYPE = {
    FIELD_AGENT: 'FIELD_AGENT',
    CONSOLIDATION_AGENT: 'CONSOLIDATION_AGENT',
};
// Phase 9: Road Alert Types
exports.ROAD_ALERT_TYPES = {
    POLICE_ACTIVE: 'POLICE_ACTIVE',
    WEIGHBRIDGE_STRICT: 'WEIGHBRIDGE_STRICT',
    ROAD_DAMAGE: 'ROAD_DAMAGE',
    FLOODING: 'FLOODING',
    FUEL_EMPTY: 'FUEL_EMPTY',
    ACCIDENT: 'ACCIDENT',
    ROAD_CLOSED: 'ROAD_CLOSED',
    CHECKPOINT_CLOSED: 'CHECKPOINT_CLOSED',
};
// Phase 9: Fuel Availability Status
exports.FUEL_AVAILABILITY_STATUS = {
    HAS_FUEL: 'HAS_FUEL',
    LIMITED: 'LIMITED',
    QUEUE_GT_1HR: 'QUEUE_GT_1HR',
    OUT: 'OUT',
};
// Phase 5: Cargo Offer Status
// CARGO_OFFER_STATUS and TRIP_STOP_STATUS are defined as Prisma enums in schema.prisma
// They are auto-generated into the Prisma client and should be imported from there if needed.
// Duplicate TypeScript enum definitions have been removed to maintain consistency.
//# sourceMappingURL=enums.js.map