import { Queue, Worker, Job } from 'bullmq';
import { Redis } from 'ioredis';
export declare const QUEUES: {
    readonly LIQUIDITY: "ruit:liquidity";
    readonly SHOCK: "ruit:shock";
    readonly OPTIMIZER: "ruit:optimizer";
    readonly INCIDENT: "ruit:incident";
    readonly NOTIFICATIONS: "ruit:notifications";
    readonly FRAUD: "ruit:fraud";
    readonly IDENTITY: "ruit:identity";
    readonly CORRIDOR: "ruit:corridor";
    readonly BEHAVIOR: "ruit:behavior";
    readonly DATA: "ruit:data";
    readonly TRUST_SCORE_UPDATE: "ruit:trust-score-update";
    readonly ESCROW_RELEASE: "ruit:escrow-release";
    readonly NOTIFICATION: "ruit:notification";
    readonly INCIDENT_ESCALATION: "ruit:incident-escalation";
    readonly CORRIDOR_SNAPSHOT: "ruit:corridor-snapshot";
    readonly SHOCK_MONITOR: "ruit:shock-monitor";
    readonly DOCUMENT_EXPIRY_CHECK: "ruit:document-expiry-check";
    readonly RATING_PROCESSOR: "ruit:rating-processor";
    readonly POD_GENERATOR: "ruit:pod-generator";
    readonly WEBHOOK_DELIVERY: "ruit:webhook-delivery";
    readonly PERFORMANCE_SNAPSHOT: "ruit:performance-snapshot";
    readonly BACKHAUL_MATCHING: "backhaul-matching";
    readonly TEMPLATE_SCHEDULER: "template-scheduler";
    readonly IDLE_ALERTS: "idle-alerts";
    readonly WEIGHBRIDGE_INTEL: "weighbridge-intelligence";
    readonly FUEL_INTEL: "fuel-intelligence";
    readonly ROUTE_DEVIATION: "route-deviation";
    readonly ZONE_DEMAND_UPDATE: "zone-demand-update";
    readonly CONSOLIDATION_MONITOR: "consolidation-monitor";
    readonly BROKER_COMMISSION: "broker-commission";
    readonly DRIVER_EARNINGS: "driver-earnings";
};
declare const redis: Redis;
export declare function getQueue(name: string): Queue;
export declare function addJob<T>(queueName: string, jobName: string, data: T, opts?: object): Promise<Job<T>>;
export declare function createWorker<T>(queueName: string, processor: (job: Job<T>) => Promise<unknown>, concurrency?: number): Worker<T>;
export { redis };
//# sourceMappingURL=index.d.ts.map